import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative">
        <div className="green-gradient w-screen z-10 h-screen fixed"></div>
        <div className=" w-screen h-screen fixed z-10 bg-pattern"></div>
        <div className="w-full relative z-20">
        <Nav></Nav>
        {children}
        <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
