'use client'

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import MegaMenu from "@/components/MegaMenu";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

import {
	motion,
	useScroll,
	useMotionValueEvent,
	useAnimation,
	AnimatePresence,
	easeInOut,
	easeOut,
} from "motion/react";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

// export const metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  // const { scrollYProgress } = useScroll()
  // const lineChartControls = useAnimation()

	// useMotionValueEvent(scrollYProgress, "change", (latest) => {
  //   console.log(latest)
  //   if (latest > 0) {
  //   lineChartControls.start({display: "none"})
  //   }
  // })

	return (
		<html lang="en">
			<body className="relative">
				<div className="green-gradient w-screen z-10 h-screen fixed"></div>
				<div className="w-[100%] h-screen fixed z-10 bg-pattern"></div>
					{/* <motion.svg
            initial={{opacity: 0}}
            whileInView={{opacity:1}}
            transition={{duration: 2}}
						width="100%"
						height="100%"
						xmlns="http://www.w3.org/2000/svg"
						className="w-full absolute -top-10 left-40 transform"
						style={{
							transform:
								"perspective(800px) rotateX(25deg) rotateY(15deg)",
							transformOrigin: "center",
						}}
					>
						<defs>
							<pattern
								id="grid"
								width="100"
								height="100"
								patternUnits="userSpaceOnUse"
							>
								<rect
									width="100"
									height="100"
									// fill="red"
									fill="transparent"
								/>
								<path
									d="M 100 0 L 0 0 0 100"
									fill="none"
									stroke="black"
									strokeWidth="0.5"
								/>
							</pattern>
						</defs>


						<rect width="100%" height="100%" fill="url(#grid)" />

						<motion.path
							d="M200 700 L300 600 L350 650 L375 550 L425 575 L550 475 L600 570 L720 420 L740 455 L850 365 L900 400 L1300 0"
							fill="none"
							strokeWidth="3"
							stroke="red"
							initial={{
								pathLength: 0,
							}}
							animate={{
								pathLength: 1,
							}}
							transition={{
								duration: 3, // Adjust animation duration
								ease: "easeInOut",
							}}
						/>


					</motion.svg>
				</div>  */}
				<div className="w-full relative z-20" id="main">
					<Nav></Nav>
					{children}
					<Footer></Footer>
				</div>
			</body>
		</html>
	);
}
